import { StyleSheet } from 'react-native';
import { colors, spacing, borderRadius, getFontStyle } from '@theme';

export const styles = StyleSheet.create({
  topHandle: {
    width: 40,
    height: 4,
    backgroundColor: colors.border.medium,
    borderRadius: borderRadius.full,
    alignSelf: 'center',
    marginBottom: spacing.lg,
  },
  communityName: {
    ...getFontStyle(12, 'medium'),
    color: colors.text.secondary,
    marginBottom: spacing.xs,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: spacing.base,
  },
  logoContainer: {
    marginRight: 12,
  },
  logo: {
    width: 100,
    height: 100,
    borderRadius: borderRadius.full,
    backgroundColor: colors.background.secondary,
    boxShadow: colors.boxShadow.midRaised,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  logoGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    experimental_backgroundImage: colors.gradient.blueRadial,
  },
  logoImage: {
    width: '100%',
    height: '100%',
    borderRadius: borderRadius.full,
  },
  logoContent: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  logoText: {
    ...getFontStyle(8, 'bold'),
    color: colors.text.white,
    textAlign: 'center',
  },
  logoSubtext: {
    ...getFontStyle(6, 'regular'),
    color: colors.text.white,
    textAlign: 'center',
    marginTop: spacing.xxs,
  },
  editIconContainer: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: colors.glass.background.white,
    width: 28,
    height: 28,
    borderRadius: borderRadius.full,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.background.white,
    overflow: 'hidden',
  },
  nameSection: {
    flex: 1,
    paddingTop: spacing.xs,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  name: {
    ...getFontStyle(20, 'bold'),
    color: colors.text.primary,
    marginRight: spacing.sm,
  },
  verifiedBadge: {
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  instagramRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.base,
  },
  instagramIcon: {
    marginRight: spacing.xs,
  },
  instagramHandle: {
    ...getFontStyle(12, 'regular'),
    color: colors.text.secondary,
  },
  statsContainer: {
    flexDirection: 'row',
    gap: spacing.sm,
    // marginBottom: spacing.sm,
  },
  statBox: {
    flex: 1,
    backgroundColor: "#FFFDEF80",
    paddingHorizontal: 4,
    paddingVertical: 6,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border.white,
  },
  statValue: {
    ...getFontStyle(16, 'bold'),
    color: colors.text.primary,
    marginBottom: spacing.xxs,
  },
  statLabel: {
    ...getFontStyle(8, 'regular'),
    color: colors.text.secondary,
  },
  description: {
    ...getFontStyle(12, 'regular'),
    color: colors.text.secondary,
    lineHeight: 20,
    marginBottom: spacing.base,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.base,
  },
  tag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF3E7',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    gap: spacing.xs,
  },
  tagText: {
    ...getFontStyle(8, 'medium'),
    color: '#FF6B35',
  },
  settingsButton: {
    position: 'absolute',
    top: spacing.xl,
    right: spacing.xl,
    padding: spacing.sm,
  },
  headerActions: {
    position: 'absolute',
    top: spacing.xl,
    right: spacing.xl,
    flexDirection: 'row',
    gap: spacing.xs,
    zIndex: 10,
  },
  actionButton: {
    padding: spacing.sm,
  },
});
