import { StyleSheet } from 'react-native';
import { colors, spacing, borderRadius, getFontStyle } from '@theme';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    experimental_backgroundImage: colors.gradient.mainBackground,
    borderRadius: borderRadius.xl,
    padding: spacing.xl,
    width: '90%',
    maxWidth: 400,
    maxHeight: '85%',
    zIndex: 10,
  },
  modalTitle: {
    ...getFontStyle(18, 'semibold'),
    color: colors.text.primary,
    marginBottom: spacing.lg,
    textAlign: 'center',
  },
  sectionTitle: {
    ...getFontStyle(14, 'semibold'),
    color: colors.text.primary,
    marginBottom: spacing.md,
  },
  selectDaysSection: {
    marginBottom: spacing.xl,
  },
  daysRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.md,
    gap: spacing.sm,
  },
  dayButton: {
    flex: 1,
    aspectRatio: 1,
    minWidth: 36,
    maxWidth: 48,
    borderRadius: borderRadius.full,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  dayButtonSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  dayButtonText: {
    ...getFontStyle(14, 'semibold'),
    color: colors.text.secondary,
  },
  dayButtonTextSelected: {
    color: colors.text.white,
  },
  endsSection: {
    marginBottom: spacing.lg,
  },
  endsOptionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xl,
    marginTop: spacing.sm,
  },
  endsOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    gap: spacing.md,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: borderRadius.sm,
    borderWidth: 2,
    borderColor: colors.border.medium,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkboxInner: {
    width: 10,
    height: 10,
    borderRadius: 2,
    backgroundColor: colors.text.white,
  },
  endsDateRow: {
    marginTop: spacing.md,
  },
  endsDateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  endsDateText: {
    ...getFontStyle(14, 'regular'),
    color: colors.text.primary,
  },
  endsDateCalendar: {
    marginTop: spacing.md,
    padding: spacing.md,
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  endsDateCalendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  endsDateCalendarNav: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  endsDateCalendarDaysRow: {
    flexDirection: 'row',
    marginBottom: spacing.xs,
  },
  endsDateCalendarDayHeader: {
    flex: 1,
    alignItems: 'center',
  },
  endsDateCalendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  endsDateCalendarCell: {
    width: '14.28%',
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  endsDateCalendarCellSelected: {
    backgroundColor: colors.primary,
    borderRadius: borderRadius.full,
  },
  customToggle: {
    paddingVertical: spacing.md,
    marginBottom: spacing.sm,
  },
  customSection: {
    marginBottom: spacing.lg,
  },
  customInput: {
    marginTop: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.background.secondary,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border.light,
    ...getFontStyle(14, 'regular'),
    color: colors.text.primary,
    minHeight: 44,
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.lg,
    paddingTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.border.light,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.button.cancel.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    ...getFontStyle(14, 'semibold'),
    color: colors.button.cancel.text,
  },
  doneButton: {
    flex: 1,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doneButtonText: {
    ...getFontStyle(14, 'semibold'),
    color: colors.text.white,
  },
});
