import { StyleSheet } from 'react-native';
import { borderRadius, colors, getFontStyle, spacing, withOpaqueForAndroid } from '@theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    experimental_backgroundImage: colors.gradient.mainBackground,
  },
  dragHandle: {
    width: 44,
    height: 4,
    borderRadius: borderRadius.full,
    backgroundColor: colors.border.medium,
    alignSelf: 'center',
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.base,
    marginBottom: spacing.md,
  },
  headerTitle: {
    ...getFontStyle(16, 'bold'),
    color: colors.text.primary,
  },
  createPill: {
    backgroundColor: '#5B8FB8',
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xs,
  },
  createPillText: {
    ...getFontStyle(8, 'semibold'),
    color: colors.text.white,
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listContent: {
    paddingHorizontal: spacing.base,
    paddingBottom: spacing.xxxl,
    gap: spacing.md,
  },
  packageCard: {
    backgroundColor: colors.glass.background.white,
    borderWidth: 1,
    borderColor: colors.border.white,
    borderRadius: borderRadius.lg,
    padding: spacing.base,
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  packageName: {
    ...getFontStyle(12, 'semibold'),
    color: colors.text.primary,
    flex: 1,
    marginRight: spacing.sm,
  },
  validityText: {
    ...getFontStyle(8, 'regular'),
    color: colors.text.secondary,
  },
  cardBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: spacing.sm,
  },
  leftMeta: {
    gap: 6,
    flex: 1,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.xl,
    flexWrap: 'wrap',
  },
  infoItem: {
    alignItems: 'flex-start',
    justifyContent: 'center',
    minWidth: 92,
  },
  infoLabel: {
    ...getFontStyle(8, 'regular'),
    color: colors.text.secondary,
  },
  infoValue: {
    ...getFontStyle(12, 'medium'),
    color: colors.text.primary,
    marginTop: 2,
  },
  tagPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: borderRadius.full,
    backgroundColor: withOpaqueForAndroid('rgba(255, 155, 68, 0.12)'),
    alignSelf: 'flex-start',
  },
  tagText: {
    ...getFontStyle(8, 'medium'),
    color: colors.text.primary,
  },
  metaText: {
    ...getFontStyle(8, 'regular'),
    color: colors.text.secondary,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  priceIcon: {
    width: 14,
    height: 14,
    resizeMode: 'contain',
  },
  priceText: {
    ...getFontStyle(12, 'semibold'),
    color: colors.text.primary,
  },
  emptyContent: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 160,
    paddingHorizontal: spacing.xl,
    gap: spacing.sm,
  },
  illustrationWrap: {
    width: 120,
    height: 120,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  userCircle: {
    width: 78,
    height: 78,
    borderRadius: borderRadius.full,
    backgroundColor: withOpaqueForAndroid('rgba(91, 143, 184, 0.18)'),
    alignItems: 'center',
    justifyContent: 'center',
  },
  plusBadge: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 26,
    height: 26,
    borderRadius: borderRadius.full,
    backgroundColor: '#6CC16C',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.background.white,
  },
  coins: {
    position: 'absolute',
    right: 2,
    top: 6,
    width: 46,
    height: 46,
    resizeMode: 'contain',
    opacity: 0.95,
  },
  title: {
    ...getFontStyle(16, 'bold'),
    color: colors.text.primary,
    textAlign: 'center',
  },
  subtitle: {
    ...getFontStyle(12, 'regular'),
    color: colors.text.secondary,
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: spacing.sm,
  },
  primaryButton: {
    backgroundColor: colors.primaryDark,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.xxxl,
    paddingVertical: spacing.md,
    minWidth: 220,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    ...getFontStyle(12, 'semibold'),
    color: colors.text.white,
  },
});
